version: '3.9'

services:

  app:
    build: ./
    ports:
      - 8080:8080


  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432

      # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_DB=postgresDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080